approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: true
author_approval: ignored
reviewers:
  -
    name: default
    required: 1
    members:
      - webbushka
      - AllanJohnson01
      - Benxamin
      - bral
      - geekingreen
      - kirstenmalin
      - marktkimball
      - ndnhat
      - osha90
      - ryoia
      - trevorlinton
      - atracy
      - berrynorth
